### ISSUE TITLE
Plugin does not work properly

### ISSUE THREAD

**Issue by Oyplap** [BuildBoy12/CustomLoadouts#1]
The plugin seems to shuffle the classes around. When I try to give (for example) class d a flashlight, medkit and coin, it gives the loadout to tutorial. Also seems to happen to other classes, its very weird.

Im using version 2.2.0

This is my config:
[config.txt](https://github.com/BuildBoy12/CustomLoadouts/files/7799863/config.txt)

I cant upload yml so i made it txt

**Comment by BuildBoy12** [comment]
Resolved in 2.2.1
